# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test_build:
    docker:
      - image: circleci/node:8.11.3-stretch
    steps:
      - checkout
      #- run:
      #    name: Test
      #    command: npm test
      - run:
          name: Build artifacts
          command: npm run prod-build
      - store_artifacts:
          path: dist/
          destination: build

workflows:
  version: 2
  "test_build":
    jobs:
      - test_build
